# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/SSC-LAB/ProiectBun/ProiectBun.srcs/sources_1/ip/mem_filter_1/mem_filter.xci
# IP: The module: 'mem_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SSC-LAB/ProiectBun/ProiectBun.srcs/sources_1/ip/mem_filter_1/mem_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_filter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/SSC-LAB/ProiectBun/ProiectBun.srcs/sources_1/ip/mem_filter_1/mem_filter.xci
# IP: The module: 'mem_filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SSC-LAB/ProiectBun/ProiectBun.srcs/sources_1/ip/mem_filter_1/mem_filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
